name : Check Security

on: pull_request

jobs: 
  lint:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        elixir: [1.13.4]
        otp: [25]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v1
        id: mix-cache-sec
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install Mix Dependencies
        if: steps.mix-cache-sec.outputs.cache-hit != 'true'
        run: mix deps.get
      - name: ==> Check Security 
        run: mix sobelow --config

